version: '3.8'  # 使用するComposeファイルのバージョンを指定

services:
  latex:
    image: ghcr.io/being24/latex-docker  # 日本語対応のTeX Liveを含む軽量なDockerイメージを指定
    volumes:
      - .:/workdir  # 現在のディレクトリをコンテナ内の/workdirにマウント
    working_dir: /workdir  # コンテナ内での作業ディレクトリを指定
    command:  # コンテナ実行時に実行するコマンドを指定
      - /bin/bash  # Bashシェルを使用
      - -c  # 次の文字列をコマンドとして実行
      - |
        # LuaLaTeXでmain.texをコンパイルしてPDFファイルを生成
        lualatex main.tex
        biber main
        lualatex main.tex
        lualatex main.tex
